
import { Product } from "../types";

export const PRODUCT_DATABASE: Product[] = [
  // WARZYWA (VEGETABLE)
  { name: "Cukinia", calories: 17, protein: 1, fats: 0, carbs: 3, unit: 'g', category: 'VEGETABLE' },
  { name: "Bakłażan", calories: 25, protein: 1, fats: 0, carbs: 6, unit: 'g', category: 'VEGETABLE' },
  { name: "Pomidor", calories: 18, protein: 1, fats: 0, carbs: 4, unit: 'g', category: 'VEGETABLE' },
  { name: "Papryka czerwona", calories: 31, protein: 1, fats: 0, carbs: 6, unit: 'g', category: 'VEGETABLE' },
  { name: "Papryka żółta", calories: 27, protein: 1, fats: 0, carbs: 5, unit: 'g', category: 'VEGETABLE' },
  { name: "Papryka zielona", calories: 20, protein: 1, fats: 0, carbs: 4, unit: 'g', category: 'VEGETABLE' },
  { name: "Brokuły", calories: 34, protein: 3, fats: 0, carbs: 7, unit: 'g', category: 'VEGETABLE' },
  { name: "Brokuł", calories: 34, protein: 3, fats: 0, carbs: 7, unit: 'g', category: 'VEGETABLE' },
  { name: "Kalafior", calories: 25, protein: 2, fats: 0, carbs: 5, unit: 'g', category: 'VEGETABLE' },
  { name: "Marchew", calories: 41, protein: 1, fats: 0, carbs: 10, unit: 'g', category: 'VEGETABLE' },
  { name: "Marchewka", calories: 41, protein: 1, fats: 0, carbs: 10, unit: 'g', category: 'VEGETABLE' },
  { name: "Pietruszka (korzeń)", calories: 36, protein: 3, fats: 1, carbs: 6, unit: 'g', category: 'VEGETABLE' },
  { name: "Seler (korzeń)", calories: 42, protein: 1, fats: 0, carbs: 9, unit: 'g', category: 'VEGETABLE' },
  { name: "Por", calories: 61, protein: 2, fats: 0, carbs: 14, unit: 'g', category: 'VEGETABLE' },
  { name: "Cebula biała", calories: 40, protein: 1, fats: 0, carbs: 9, unit: 'g', category: 'VEGETABLE' },
  { name: "Cebula czerwona", calories: 40, protein: 1, fats: 0, carbs: 9, unit: 'g', category: 'VEGETABLE' },
  { name: "Cebula", calories: 40, protein: 1, fats: 0, carbs: 9, unit: 'g', category: 'VEGETABLE' },
  { name: "Czosnek", calories: 149, protein: 6, fats: 0, carbs: 33, unit: 'g', category: 'VEGETABLE' },
  { name: "Szpinak świeży", calories: 23, protein: 3, fats: 0, carbs: 4, unit: 'g', category: 'VEGETABLE' },
  { name: "Szpinak", calories: 23, protein: 3, fats: 0, carbs: 4, unit: 'g', category: 'VEGETABLE' },
  { name: "Pieczarki", calories: 22, protein: 3, fats: 0, carbs: 3, unit: 'g', category: 'VEGETABLE' },
  { name: "Fasolka szparagowa", calories: 31, protein: 2, fats: 0, carbs: 7, unit: 'g', category: 'VEGETABLE' },
  { name: "Groszek mrożony", calories: 81, protein: 5, fats: 0, carbs: 14, unit: 'g', category: 'VEGETABLE' },
  { name: "Kukurydza konserwowa", calories: 86, protein: 3, fats: 1, carbs: 19, unit: 'g', category: 'VEGETABLE' },
  { name: "Buraki gotowane", calories: 43, protein: 2, fats: 0, carbs: 10, unit: 'g', category: 'VEGETABLE' },
  { name: "Burak gotowany", calories: 43, protein: 2, fats: 0, carbs: 10, unit: 'g', category: 'VEGETABLE' },
  { name: "Rzodkiewka", calories: 16, protein: 1, fats: 0, carbs: 4, unit: 'g', category: 'VEGETABLE' },
  { name: "Ogórek", calories: 15, protein: 1, fats: 0, carbs: 3, unit: 'g', category: 'VEGETABLE' },
  { name: "Ogórek kiszony", calories: 11, protein: 1, fats: 0, carbs: 2, unit: 'g', category: 'VEGETABLE' },

  // OWOCE (FRUIT)
  { name: "Ananas", calories: 50, protein: 1, fats: 0, carbs: 13, unit: 'g', category: 'FRUIT' },
  { name: "Ananas świeży", calories: 50, protein: 1, fats: 0, carbs: 13, unit: 'g', category: 'FRUIT' },
  { name: "Mango", calories: 60, protein: 1, fats: 0, carbs: 15, unit: 'g', category: 'FRUIT' },
  { name: "Awokado", calories: 160, protein: 2, fats: 15, carbs: 9, unit: 'g', category: 'FAT' },
  { name: "Truskawki", calories: 33, protein: 1, fats: 0, carbs: 8, unit: 'g', category: 'FRUIT' },
  { name: "Borówki", calories: 57, protein: 1, fats: 0, carbs: 14, unit: 'g', category: 'FRUIT' },
  { name: "Maliny", calories: 52, protein: 1, fats: 0, carbs: 12, unit: 'g', category: 'FRUIT' },
  { name: "Jabłko", calories: 52, protein: 0, fats: 0, carbs: 14, unit: 'g', category: 'FRUIT' },
  { name: "Banan", calories: 89, protein: 1, fats: 0, carbs: 23, unit: 'g', category: 'FRUIT' },
  { name: "Gruszka", calories: 57, protein: 0, fats: 0, carbs: 15, unit: 'g', category: 'FRUIT' },
  { name: "Pomarańcza", calories: 47, protein: 1, fats: 0, carbs: 12, unit: 'g', category: 'FRUIT' },
  { name: "Kiwi", calories: 61, protein: 1, fats: 1, carbs: 15, unit: 'g', category: 'FRUIT' },

  // BIAŁKO (PROTEIN)
  { name: "Pierś kurczaka", calories: 110, protein: 21, fats: 1, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Pierś z kurczaka", calories: 110, protein: 21, fats: 1, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Kurczak", calories: 110, protein: 21, fats: 1, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Udo z kurczaka bez skóry", calories: 120, protein: 19, fats: 5, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Pierś indyka", calories: 105, protein: 22, fats: 1, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Pierś z indyka", calories: 105, protein: 22, fats: 1, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Indyk", calories: 105, protein: 22, fats: 1, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Wołowina chuda (ligawa)", calories: 140, protein: 22, fats: 5, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Wołowina mielona chuda", calories: 160, protein: 19, fats: 9, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Polędwica wołowa", calories: 130, protein: 22, fats: 4, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Mięso mielone z indyka", calories: 120, protein: 20, fats: 4, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Indyk mielony", calories: 120, protein: 20, fats: 4, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Schab bez kości", calories: 120, protein: 22, fats: 3, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Schab wieprzowy", calories: 120, protein: 22, fats: 3, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Polędwiczka wieprzowa", calories: 110, protein: 21, fats: 2, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Łosoś świeży", calories: 208, protein: 20, fats: 13, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Tuńczyk (puszka)", calories: 116, protein: 26, fats: 1, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Makrela wędzona", calories: 305, protein: 18, fats: 25, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Pstrąg wędzony", calories: 150, protein: 22, fats: 6, carbs: 0, unit: 'g', category: 'PROTEIN' },
  { name: "Jajko (rozmiar L)", calories: 143, protein: 13, fats: 10, carbs: 1, unit: 'g', category: 'PROTEIN' },
  { name: "Szynka drobiowa", calories: 100, protein: 18, fats: 2, carbs: 1, unit: 'g', category: 'PROTEIN' },

  // WĘGLOWODANY (CARB)
  { name: "Ziemniaki", calories: 77, protein: 2, fats: 0, carbs: 17, unit: 'g', category: 'CARB' },
  { name: "Bataty", calories: 86, protein: 2, fats: 0, carbs: 20, unit: 'g', category: 'CARB' },
  { name: "Batat", calories: 86, protein: 2, fats: 0, carbs: 20, unit: 'g', category: 'CARB' },
  { name: "Ryż basmati (suchy)", calories: 350, protein: 8, fats: 1, carbs: 78, unit: 'g', category: 'CARB' },
  { name: "Ryż", calories: 350, protein: 8, fats: 1, carbs: 78, unit: 'g', category: 'CARB' },
  { name: "Ryż jaśminowy", calories: 350, protein: 8, fats: 1, carbs: 78, unit: 'g', category: 'CARB' },
  { name: "Kasza gryczana", calories: 340, protein: 12, fats: 3, carbs: 70, unit: 'g', category: 'CARB' },
  { name: "Kasza gryczana (sucha)", calories: 340, protein: 12, fats: 3, carbs: 70, unit: 'g', category: 'CARB' },
  { name: "Kasza pęczak", calories: 350, protein: 10, fats: 2, carbs: 75, unit: 'g', category: 'CARB' },
  { name: "Kasza jaglana", calories: 350, protein: 11, fats: 3, carbs: 71, unit: 'g', category: 'CARB' },
  { name: "Komosa ryżowa", calories: 368, protein: 14, fats: 6, carbs: 64, unit: 'g', category: 'CARB' },
  { name: "Makaron pełnoziarnisty", calories: 350, protein: 14, fats: 3, carbs: 65, unit: 'g', category: 'CARB' },
  { name: "Spaghetti", calories: 350, protein: 12, fats: 1, carbs: 72, unit: 'g', category: 'CARB' },
  { name: "Makaron", calories: 350, protein: 12, fats: 1, carbs: 72, unit: 'g', category: 'CARB' },
  { name: "Chleb żytni", calories: 250, protein: 6, fats: 2, carbs: 48, unit: 'g', category: 'CARB' },
  { name: "Grahamka", calories: 260, protein: 9, fats: 2, carbs: 50, unit: 'g', category: 'CARB' },
  { name: "Płatki owsiane", calories: 380, protein: 13, fats: 7, carbs: 66, unit: 'g', category: 'CARB' },

  // NABIAŁ (DAIRY)
  { name: "Jogurt naturalny", calories: 61, protein: 4, fats: 3, carbs: 5, unit: 'g', category: 'DAIRY' },
  { name: "Skyr naturalny", calories: 65, protein: 12, fats: 0, carbs: 4, unit: 'g', category: 'DAIRY' },
  { name: "Twaróg chudy", calories: 90, protein: 20, fats: 0, carbs: 4, unit: 'g', category: 'DAIRY' },
  { name: "Serek wiejski lekki", calories: 80, protein: 11, fats: 3, carbs: 2, unit: 'g', category: 'DAIRY' },
  { name: "Mleko 1.5%", calories: 45, protein: 3, fats: 2, carbs: 5, unit: 'ml', category: 'DAIRY' },
  { name: "Ser Mozzarella Light", calories: 160, protein: 19, fats: 9, carbs: 1, unit: 'g', category: 'DAIRY' },
  { name: "Ser Feta Light", calories: 180, protein: 17, fats: 12, carbs: 1, unit: 'g', category: 'DAIRY' },
  { name: "Maślanka", calories: 40, protein: 3, fats: 1, carbs: 5, unit: 'ml', category: 'DAIRY' },

  // TŁUSZCZE (FAT)
  { name: "Oliwa z oliwek", calories: 884, protein: 0, fats: 100, carbs: 0, unit: 'ml', category: 'FAT' },
  { name: "Masło orzechowe", calories: 590, protein: 25, fats: 50, carbs: 13, unit: 'g', category: 'FAT' },
  { name: "Nasiona Chia", calories: 486, protein: 17, fats: 31, carbs: 42, unit: 'g', category: 'FAT' },
  { name: "Wiórki kokosowe", calories: 660, protein: 7, fats: 65, carbs: 24, unit: 'g', category: 'FAT' },
  { name: "Masło", calories: 717, protein: 1, fats: 81, carbs: 1, unit: 'g', category: 'FAT' },
  { name: "Pesto zielone", calories: 450, protein: 5, fats: 45, carbs: 6, unit: 'g', category: 'FAT' }
];
